name: workflow2
on:
  workflow_dispatch:
  
jobs:
  job1:
    name: job1 name
    runs-on: ubuntu-latest
    steps:
      - name: job1 step1
        run: echo "job1 step1"
  job2:
    name: job1 name
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: job2 step1
        run: echo "job2 step1"
