name: workflow2
on:
  workflow_dispatch:
    inputs:
      sha:
        required: true
        type: string
  
jobs:
  job1:
    name: job1 name
    runs-on: ubuntu-latest
    steps:
      - name: job1 step1
        run: echo "job1 step1"
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run only if input exist (Validate input hash)
        if: ${{ github.event.inputs.sha != '' }}
        run: git cat-file -e ${{ github.event.inputs.sha }}^{commit}

  job2:
    name: job2 name
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: job2 step1
        run: echo "job2 step1"
